<MyLayout>
     BoxLayout:
          orientation: "vertical"
          size: root.width, root.height

          padding: 50
          spacing: 20

          Button:
               text: "Hello World"

          Button:
               text: "Yo Yo World"

          Button:
               text: "What's Up World?"
               pos_hint: {'center_x': 0.5}
               size_hint: (.5, .5)
               #width: 200
               #height: 50