<Button>
    font_size: 32
    background_normal: ''
    background_color: (0,0,1,1)

<TextInput>
    background_color: (150/250,150/250,150/250,1)

<MyLayout>

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        #padding:10
        #spacing:10

        Image:
            source: 'images/mushiandme.jpeg'
            allow_stretch: True
            keep_ratio: False

        #Button:
            text: "Clear"
            background_color: (1,0,0,1)